### ISSUE TITLE
HTML tags should be escaped

### ISSUE THREAD

**Issue by deanpcmad** [vercel/og-image#144]
I've just found this app and it looks really neat. While playing around with the example I found that any html tags can be added, which can be a security risk.

For example, adding the iframe tag:
`https://og-image.vercel.app/**Hello**%20World%20%3Ciframe%20src='https:/deanpcmad.com/testfile.html'/%3E.png?fontSize=100px&theme=light&md=1`

Renders out an image with an iframe:

![test](https://user-images.githubusercontent.com/425200/103755180-50778200-5005-11eb-8420-ce1a914b3dd4.png)

I'm not sure if this is by design, I just feel html tags should be escaped?

**Comment by styfle** [comment]
Hi @deanpcmad 

This is expected when the `md=1` option is used since markdown accepts arbitrary html.

You can use `md=0` to use literal text instead.

You could also add something like [`sanitize-html`](https://www.npmjs.com/package/sanitize-html) or [`dompurify`](https://www.npmjs.com/package/dompurify) if you wanted to narrow down the accepted list of html tags.

**Comment by leerob** [comment]
Closing in favor of https://github.com/vercel/og-image/issues/226
